#+TITLE: Emacs Configuration
#+AUTHOR: Andrei Maxim
#+DATE: Sat Dec 15 15:38:00 2018
#+PROPERTY: header-args :tangle yes

This is a beginner's configuration file that should allow somebody (like one of
my co-workers) to download Emacs (v26 or higher), clone this repository and start
being productive basically as quickly as possible, with most of the features you
would normally find in other editors like Sublime, Atom, Visual Studio Code or
IDEs like RubyMine together with some instructions on how to use those
features.

So, all you need to do to get started is to copy the =.emacs.d= folder in your
=$HOME= directory (=/Users/<your account/= on macOS, =/home/<your account>= on 
Linux and probably =C:\Users\<your account>\AppData\Roaming\= on Windows) and
then start Emacs.

Since Emacs is highly portable, it should work fine on all operating systems,
including Windows, but there is a chance that you'll probably need to do some
tinkering for some packages to work correctly.

If you are looking for an actual Emacs starter kit, there are several great ones 
available:

 - [[http://spacemacs.org/][Spacemacs]], which should be a nice transition for people coming from Vim
 - [[https://github.com/hlissner/doom-emacs][Doom]], another started kit for Vim users
 - [[https://github.com/purcell/emacs.d][Steve Purcell's emacs.d]], which is a "reasonable Emacs config"
 - [[https://github.com/bbatsov/prelude][Prelude]], an opinionated Emacs config

Also, there is a collection of [[https://github.com/caisah/emacs.dz][awesome Emacs configurations]] from various
people, should you need inspiration.

The format of the file is based on the idea of [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]] promoted by
Donald E. Knuth. The format is extremely useful especially for editor
configuration files like Vim or Emacs because people tend to spend initially
a lot of time to set up the editor environment and then a lot of time passes
before having to edit the file again.

Fortunately, Emacs is flexible enough to be able to load this file, parse the
code blocks and use that as the configuration at start-up. All that's required
is a tiny snippet in your Emacs =init.el= file:

#+begin_src emacs-lisp :tangle no
(require 'org)
(org-babel-load-file (expand-file-name "README.org" user-emacs-directory))
#+end_src


* Package Management

By default, Emacs has just one repository enabled, and that is [[https://elpa.gnu.org/][GNU ELPA]] 
(which stands for Emacs Lisp Package Archive). Since the packages are
signed, it's slightly more secure. The only downside is that it requires
all packages to be released under some sort of FSF-compliant license,
which is not always the case.

The [[https://melpa.org/][MELPA]] package repository is a commonly-used third-party package
archive that ignores the license requirements of ELPA. Also, it pulls
the data automatically from the master branch of the git repo, so
package developers no longer need to do a release.

There is also a /stable/ version of MELPA, but it's under maintenance.

#+begin_src emacs-lisp
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/"))
#+end_src

Org mode, the Emacs major mode used to write this file, also has a
package archive.

#+begin_src emacs-lisp
(add-to-list 'package-archives
             '("org" . "https://orgmode.org/elpa/") t)
#+end_src

In order to actually enable packages, John Wiegley's excellent [[https://github.com/jwiegley/use-package][use-package]] is 
used as it allows to declaratively configure packages quite easily.

#+begin_src emacs-lisp
(eval-when-compile
  (require 'use-package))
#+end_src

Once that is loaded, add the =use-package-ensure-system-package= package (now that's
a mouthful) which adds the =ensure-system-package= keyword, which checks the exec
path for the specified binaries.

#+begin_src emacs-lisp
(use-package use-package-ensure-system-package
  :ensure t)
#+end_src

=use-package= does not auto-update packages:

#+begin_src emacs-lisp
(use-package auto-package-update
  :ensure t
  :config
  (setq auto-package-update-delete-old-versions t)
  (setq auto-package-update-hide-results t)
  (auto-package-update-maybe))
#+end_src


** Customize the customizations!

Various customization settings can be done from within Emacs, which will
add some emacs code at the end of the =init.el=. In some cases, it might
mess up the configuration, so this should configure Emacs to work with a
separate =.custom.el= for customizations.

#+begin_src emacs-lisp
(setq-default custom-file (expand-file-name ".custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file))
#+end_src

** Dedicated space for private information

Store private settings like API tokens, keys, host names and so on  in a 
=.secrets.el= file, which should be ignored by the version control system.

#+begin_src emacs-lisp
(let ((secret.el (expand-file-name ".secret.el" user-emacs-directory)))
  (when (file-exists-p secret.el)
    (load secret.el)))
#+end_src

* User Experience

First, start with a good set of defaults based on Phil Hagelberg's
=better-defaults= package.

Remove the menubar, the toolbar and scrollbars:

#+begin_src emacs-lisp
(menu-bar-mode -1)
(when (fboundp 'tool-bar-mode)
  (tool-bar-mode -1))
(when (fboundp 'scroll-bar-mode)
  (scroll-bar-mode -1))
(when (fboundp 'horizontal-scroll-bar-mode)
  (horizontal-scroll-bar-mode -1))
#+end_src

Configure Emacs to delete characters /up to/ the specified character, just like
other editors would normally do:

#+begin_src emacs-lisp
(autoload 'zap-up-to-char "misc"
  "Kill up to, but not including ARGth occurrence of CHAR." t)
#+end_src

If there are multiple buffers with the same name Emacs will simply add a number,
like =<2>= or =<3>=, which is not helpful. This will tell Emacs to add the
name of the folder before the name of the file, in case there are multiple buffers
with the same name.

So, in case there is a =src/foo/Makefile= and a =src/bar/Makefile=, the buffer
names will be =foo/Makefile= and =bar/Makefile=.

#+begin_src emacs-lisp
(require 'uniquify)
(setq uniquify-buffer-name-style 'forward)
#+end_src

Remember the last place a file was visited:

#+begin_src emacs-lisp
(require 'saveplace)
(setq-default save-place t)
#+end_src

** Default settings

Avoid loading outdated compiled files:

#+begin_src emacs-lisp
(setq load-prefer-newer t)
#+end_src

Do not display the default start-up screen:

#+begin_src emacs-lisp
(setq-default inhibit-startup-screen t)
#+end_src

Show an empty scratch buffer:

#+begin_src emacs-lisp
(setq-default initial-scratch-message "")
#+end_src

Always use UTF-8:

#+begin_src emacs-lisp
(set-default-coding-systems 'utf-8)
#+end_src

Always indent using spaces instead of tabs:

#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
#+end_src

When copying to the clipboard, add the existing contents of the clipboard to
Emacs's kill ring so it's not completely lost.

#+begin_src emacs-lisp
(setq save-interprogram-paste-before-kill t)
#+end_src

Add a final newline to files:

#+begin_src emacs-lisp
(setq-default require-final-newline t)
#+end_src

Use only a visible bell:

#+begin_src emacs-lisp
(setq-default visible-bell t)
#+end_src

Store the backups in a dedicated folder and perform some automated cleanup:

#+begin_src emacs-lisp
(setq backup-directory-alist `(("." . ,(concat user-emacs-directory
                                               "backups")))
      backup-by-copying t
      version-control t
      delete-old-versions t
      kept-new-versions 20
      kept-old-versions 5)
#+end_src

Always confirm before exiting Emacs:

#+begin_src emacs-lisp
(setq-default confirm-kill-emacs 'yes-or-no-p)
#+end_src

** Global shortcuts

Use =Meta-/= to expand the word before the point, based on patterns or the text
already inserted in the buffer:

#+begin_src emacs-lisp
(global-set-key (kbd "M-/") 'hippie-expand)
#+end_src

Bind =C-x C-b= to the more enhanced =ibuffer= instead of the default Emacs command 
that lists buffers:

#+begin_src emacs-lisp
(global-set-key (kbd "C-x C-b") 'ibuffer)
#+end_src

Bind =M-z= to use the aforementioned =zap-up-to-char= function:

#+begin_src emacs-lisp
(global-set-key (kbd "M-z") 'zap-up-to-char)
#+end_src

Use the [[https://github.com/bbatsov/crux][crux]] package to define some interactive commands that might improve
the overall experience when working with indented code.

The new shortcuts are:

 - =C-a= to move to the first non-whitespace character on the line and use 
   =C-a= again to move to the beginning of the line
 - =C-k= to kill all the characters from point to the end of the line and
   use =C-k= again to remove the newline character
 - =C-<backspace>= to remove all the characters from point to the beginning
   of the line and adjust indentation
 - =C-c n= fix indentation for the selected region or the whole buffer
 - =C-c r= rename the existing buffer and, if it's a file, rename it too

#+begin_src emacs-lisp
(use-package crux
  :ensure t
  :bind (("C-a" . crux-move-beginning-of-line)
         ("C-k" . crux-smart-kill-line)
         ("C-<backspace>" . crux-kill-line-backwards)
         ("C-c n" . crux-cleanup-buffer-or-region)
         ("C-c r" . crux-rename-file-and-buffer)))
#+end_src

** Theme

I've grown accustomed to the [[https://www.fsd.it/shop/fonts/pragmatapro/][Pragmata Pro]] font, which can feel a bit too narrow
at first, especially on big screens, but it's extremely legible on a regular 
laptop screen.

Getting all the weights and variants is quite expensive (roughly 199 Euros), but
you can easily get away with the Essentials pack, especially if you're not into
ligatures. 

#+begin_src emacs-lisp
(set-frame-font "Essential PragmataPro-13")
#+end_src



#+begin_src emacs-lisp
(use-package highlight-indentation-guide
  :ensure t
  :hook prog-mode
  :config (setq highlight-indent-guides-method 'character))

(use-package highlight-numbers)


;; Funky modeline, from the Doom project
(use-package dash)
(use-package all-the-icons)
(use-package eldoc-eval
  :config
  (eldoc-in-minibuffer-mode 1))

(use-package doom-modeline
  :config
  (setq doom-modeline-height 27
        doom-modeline-bar-width 1
        doom-modeline-buffer-file-name-style 'truncate-except-project)
  (doom-modeline-init))

(use-package doom-themes
  :config
  (load-theme 'doom-one t)
  (doom-themes-org-config)
  (doom-themes-neotree-config))

(use-package fill-column-indicator)
(use-package git-gutter-fringe
  :ensure t
  :config
  (global-git-gutter-mode +1))

(use-package ace-window
  :commands
  (ace-window ace-swap-window ace-delete-window
              ace-select-window ace-delete-other-windows)
  :init
  (define-key global-map [remap other-window] #'ace-window))

(use-package paren
  :ensure nil
  :config
  (show-paren-mode t))

(use-package hl-line
  :ensure nil
  :config
  (global-hl-line-mode))

;; (use-package highlight-numbers
;;   :ensure t
;;   :hook
;;   (prog-mode . highlight-numbers-mode))

(use-package which-key
  :config
  (which-key-mode))

;; Always show the column number
(setq column-number-mode t)
;; Use the 26+ mode to display line numbers
(global-display-line-numbers-mode)
#+end_src

* Tools

#+begin_src emacs-lisp
;; Auto refresh buffers
(global-auto-revert-mode 1)

;; Also auto refresh dired, but be quiet about it
(setq global-auto-revert-non-file-buffers t)
(setq auto-revert-verbose nil)

(use-package auto-package-update
  :ensure t
  :config
  (setq auto-package-update-delete-old-versions t
        auto-package-update-interval 4)
  (auto-package-update-maybe))

(use-package flx)

(use-package ivy
  :demand
  :config
  (setq ivy-use-virtual-buffers t
        ivy-count-format "%d/%d "
        ivy-re-builders-alist '((swiper . ivy--regex-plus)
                                (counsel-ag . ivy--regex-plus)
                                (t . ivy--regex-fuzzy))
        ivy-initial-inputs-alist nil)
  (ivy-mode 1))

(use-package ivy-hydra)

(use-package counsel
  :bind
  (("M-x" . counsel-M-x) 
   ("C-x C-f" . counsel-find-file)
   ("C-c a" . counsel-ag)))

(use-package counsel-gtags
  :bind
  ("M-t" . counsel-gtags-find-definition)
  ("M-r" . counsel-gtags-find-reference)
  ("M-s" . counsel-gtags-find-symbol)
  ("M-," . counsel-gtags-go-backward))

(use-package counsel-projectile)

(use-package swiper
  :bind
  (("C-s" . swiper)))

(use-package company
  :commands (company-mode global-company-mode company-complete
                          company-complete-common company-manual-begin company-grab-line)
  :config
  (setq company-idle-delay nil
        company-tooltip-limit 10
        company-dabbrev-downcase nil
        company-dabbrev-ignore-case nil
        company-dabbrev-code-other-buffers t
        company-tooltip-align-annotations t
        company-require-match 'never
        company-global-modes '(not eshell-mode comint-mode erc-mode message-mode help-mode gud-mode)
        company-frontends '(company-pseudo-tooltip-frontend company-echo-metadata-frontend)
        company-backends '(company-capf company-dabbrev company-ispell)
        company-transformers '(company-sort-by-occurrence))
  (global-company-mode +1))

(use-package flycheck)
(use-package flycheck-pos-tip)
(use-package flyspell-correct-ivy)

(use-package company-dict)

(use-package company-quickhelp
  :after company
  :config
  (setq company-quickhelp-delay nil)
  (company-quickhelp-mode +1))


(use-package dired-k
  :config
  (setq dired-k-style 'git))
(use-package ggtags)
(use-package better-defaults)

(use-package rainbow-delimiters
  :config
  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
(use-package smartparens
  :config
  (smartparens-global-mode))

(use-package git-timemachine)
(use-package gitconfig-mode)
(use-package gitignore-mode)
(use-package magit
  :config
  (setq magit-completing-read-function 'ivy-completing-read
        magit-status-fullscreen t
        magit-repository-directories '("~/src/")))

(use-package aggressive-indent
  :config 
  (global-aggressive-indent-mode 1)
  (add-to-list 'aggressive-indent-excluded-modes 'html-mode))

(use-package multi-term
  :commands
  (multi-term multi-term-next multi-term-prev)
  :config
  (setq multi-term-program (getenv "SHELL")
        multi-term-switch-after-close 'PREVIOUS))

(use-package neotree
  :commands (neotree-show
             neotree-hide
             neotree-toggle
             neotree-dir
             neotree-find
             neo-global--with-buffer
             neo-global--window-exists-p)
  :config
  (setq neo-create-file-auto-open nil
        neo-auto-indent-point nil
        neo-autorefresh nil
        neo-mode-line-type 'none
        neo-window-width 70
        neo-show-updir-line nil
        neo-theme 'nerd ; fallback
        neo-banner-message nil
        neo-confirm-create-file #'off-p
        neo-confirm-create-directory #'off-p
        neo-show-hidden-files nil
        neo-keymap-style 'concise
        neo-hidden-regexp-list
        '(;; vcs folders
          "^\\.\\(git\\|hg\\|svn\\)$"
          ;; compiled files
          "\\.\\(pyc\\|o\\|elc\\|lock\\|css.map\\)$"
          ;; generated files, caches or local pkgs
          "^\\(node_modules\\|vendor\\|.\\(project\\|cask\\|yardoc\\|sass-cache\\)\\)$"
          ;; org-mode folders
          "^\\.\\(sync\\|export\\|attach\\)$"
          "~$"
          "^#.*#$"))

  (when (bound-and-true-p winner-mode)
    (push neo-buffer-name winner-boring-buffers)))

(use-package projectile
  :ensure t
  :config
  (setq projectile-completion-system 'ivy
        projectile-project-search-path '("~/src/")
        projectile-git-command "fd . --hidden --no-ignore-vcs --print0 --color never --ignore-file ~/.fdrc"
        projectile-indexing-method 'alien)
  (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
  (projectile-mode)
  )

(use-package ibuffer-projectile)

(use-package restclient
  :mode ("\\.http\\'" . restclient-mode))

#+end_src

* Ruby programming

#+begin_src emacs-lisp
(use-package bundler)

(use-package enh-ruby-mode
  :ensure-system-package
  ((rubocop     . "gem install rubocop")
   (ruby-lint   . "gem install ruby-lint")
   (ripper-tags . "gem install ripper-tags")
   (pry         . "gem install pry")))
  :mode (("Appraisals\\'" . enh-ruby-mode)
         ("\\(Rake\\|Thor\\|Guard\\|Gem\\|Cap\\|Vagrant\\|Berks\\|Pod\\|Puppet\\)file\\'" . enh-ruby-mode)
         ("\\.\\(rb\\|rabl\\|ru\\|builder\\|rake\\|thor\\|gemspec\\|jbuilder\\)\\'" . enh-ruby-mode))
  :interpreter "ruby"
  :init
  (progn
    (setq enh-ruby-deep-indent-paren nil
          enh-ruby-hanging-paren-deep-indent-level 2)))

(use-package flycheck
  :init
  (add-hook 'prog-mode-hook 'global-flycheck-mode)
  (setq flycheck-ruby-rubocop-executable "/usr/local/bin/rubocop"))

(use-package inf-ruby
  :hook (enh-ruby-mode . inf-ruby-minor)
  :init
  (add-hook 'compilation-filter-hook 'inf-ruby-auto-enter))

(use-package minitest)
(use-package rbenv
  :hook (enh-ruby-mode . rbenv))
(use-package robe
  :init
  (add-hook 'enh-ruby-mode-hook 'robe-mode))

(use-package rspec-mode)
(use-package ruby-test-mode)
(use-package ruby-tools)
(use-package rake)
(use-package yard-mode
  :init
  (add-hook 'enh-ruby-mode-hook 'eldoc-mode)
  (add-hook 'enh-ruby-mode-hook 'yard-mode))

;; (use-package rcodetools
;;   :load-path "modules"
;;   :bind (:map ruby-mode-map
;;               ("C-c C-c" . xmp)))
#+end_src

* Clojure

Install cider and Clojure mode.

#+begin_src emacs-lisp
(use-package cider)
(use-package clojure-mode)
#+end_src

* Data

TBD

* Blogging

TBD
* Org mode

Found on [[https://github.com/danielmai/.emacs.d/blob/master/config.org][this]] config:

#+begin_src emacs-lisp
(bind-key "C-c l" 'org-store-link)
(bind-key "C-c c" 'org-capture)
(bind-key "C-c a" 'org-agenda)

(setq org-src-fontify-natively t
      org-src-window-setup 'current-window
      org-src-strip-leading-and-trailing-blank-lines t
      org-src-preserve-indentation t
      org-src-tab-acts-natively t)

(add-to-list 'org-structure-template-alist '("el" "#+BEGIN_SRC emacs-lisp\n?\n#+END_SRC" ""))
(add-to-list 'org-structure-template-alist '("rb" "#+BEGIN_SRC ruby\n?\n#+END_SRC" ""))
(add-to-list 'org-structure-template-alist '("sh" "#+BEGIN_SRC sh\n?\n#+END_SRC" ""))
(add-to-list 'org-structure-template-alist '("md" "#+BEGIN_SRC markdown\n?\n#+END_SRC" ""))
(add-to-list 'org-structure-template-alist '("gq" "#+BEGIN_SRC graphql\n?\n#+END_SRC" ""))
#+end_src


